[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["package.json"]

[[redirects]]
  from = "/api/send-otp"
  to = "/.netlify/functions/send-otp"
  status = 200

[[redirects]]
  from = "/api/applications"
  to = "/.netlify/functions/applications"
  status = 200

[[redirects]]
  from = "/api/student-applications"
  to = "/.netlify/functions/applications?type=student"
  status = 200

[[redirects]]
  from = "/api/colleges"
  to = "/.netlify/functions/applications?type=colleges"
  status = 200

[[redirects]]
  from = "/api/instructors"
  to = "/.netlify/functions/applications?type=instructors"
  status = 200

[[redirects]]
  from = "/api/students"
  to = "/.netlify/functions/applications?type=students"
  status = 200

[[redirects]]
  from = "/api/cases"
  to = "/.netlify/functions/applications?type=cases"
  status = 200


